title: SeqAn
author:
  name: SeqAn
  email: support@seqan.de
description: > # this means to ignore newlines until "show_excerpts:"
  SeqAn is an open source C++ library of efficient algorithms and data
  structures for the analysis of sequences with the focus on biological data.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: "seqan"
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: SeqAnLib
    github:  seqan
    gitter: seqan/Lobby
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

collections:
  people:
  apps:
    output: true

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- 01_news.md
- 02_getting_started.md
- 03_people.md
- 04_applications.md
- 05_publications.md
- 06_contact.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jemoji
